### ISSUE TITLE
Detect and convert to subdomain URL's

### ISSUE THREAD

**Issue by dokterbob** [PinataCloud/ipfs-gateway-tools#3]
Gateway URL's should be transformed to `<root_cid>.ipfs.gatewaydomain` instead of using `/ipfs/` or `/ipns` otherwise all IPFS resources share the same security context!

This is a big security concern!

Background: https://consensys.net/diligence/blog/2021/06/ipfs-gateway-security/

**Comment by dokterbob** [comment]
Ref: https://github.com/ipfs/in-web-browsers/issues/89

**Comment by polluterofminds** [comment]
I believe this is resolved with this commit: https://github.com/PinataCloud/ipfs-gateway-tools/commit/18b9b1e5e866aa44991a6a2d922b81e5343cebfc

Heads up though, this did introduce a bug where full path filenames aren't working (i.e. ipfs/CID/myfile.png). There's a bug open and we'll hopefully have a fix for that soon. https://github.com/PinataCloud/ipfs-gateway-tools/issues/11
