### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by ErlanBazarov** [PinataCloud/ipfs-gateway-tools#7]
When trying to do `const ipfsGatewayTools = require('@pinata/ipfs-gateway-tools');` I receive error `Error: Cannot find module '@pinata/ipfs-gateway-tools'`. I did run `npm install @pinata/ipfs-gateway-tools`

Node version is 16.13.1. My `package.json` has these lines in dependencies:      
```
"@pinata/ipfs-gateway-tools": "^1.2.0",
"@pinata/sdk": "^1.1.23",
```

**Comment by rommel-pinata** [comment]
Hello @ErlanBazarov, 

Remember to use the `dist` path in your require statement.

```
const IPFSGatewayTools = require('@pinata/ipfs-gateway-tools/dist/node');
const gatewayTools = new IPFSGatewayTools();
```

[More info](https://github.com/PinataCloud/ipfs-gateway-tools#nodejs-setup)

Let me know if this solve your problem.
