### ISSUE TITLE
Output URL Error 

### ISSUE THREAD

**Issue by stevedsimkins** [PinataCloud/ipfs-gateway-tools#8]
From anon-user: 

Hello there, I was just letting you guys know that a bug was introduced into the @pinata/ipfs-gateway-tools version: 1.2.0 on the convertToDesiredGateway function. The update removes the file path string at the end of the IPFS URL. The most recent published code on GitHub is for version 1.1.0 so I can't help much more beyond just providing some steps to reproduce.

Input:
sourceUrl = "ipfs://QmatEuRrPqqHQPPM2uiVPa4RbHcD7NCpuYEbbX6LMcPYhD/0.json"

desiredGateway = "https://mtcrypto.mypinata.cloud"

On Version 1.2.0 (Broken) Output:
https://mtcrypto.mypinata.cloud/ipfs/QmatEuRrPqqHQPPM2uiVPa4RbHcD7NCpuYEbbX6LMcPYhD (Missing "/0.json" at end)

On Version 1.1.6 (Working) Output:
https://mtcrypto.mypinata.cloud/ipfs/QmatEuRrPqqHQPPM2uiVPa4RbHcD7NCpuYEbbX6LMcPYhD/0.json (Has file "/0.json" at the end of string)

I'm going to revert to version 1.1.6 as that works fine for my purposes but I just thought I would bring that to your attention. Thanks and have a nice day!

**Comment by surfer77** [comment]
have the same error. also seems the gh version is not the latest version of the package so can't help to do a pull request.
